#!/bin/bash


sql_root="root"
sql_pass=""


if [ -s dbdata.txt ];
then

    cat dbdata.txt | while read line
    do
      mysql --user="$sql_root" -e "show databases;
      use test22;
      show tables;
      select * from $line; "
    done
else [ERROR] Databases were not created
fi 

