#!/bin/bash

if [ -s remlog.txt ];
  then
    cat remlog.txt | while read line
      do
        if [ -d $line ]; 
        then 
          echo Dir $line exist; 
        else 
          echo Dir $line was removed;
        fi
      done;
else
  echo No empty folders were detected;
fi
