#!/bin/bash

if [ -s logrem.txt ];
  then
    cat logrem.txt | while read line
      do
        if [ -d $line ]; 
        then 
          echo Dir $line exists; 
        else 
          echo Dir $line was removed;
        fi
      done;
else
  echo No empty folders were detected;
fi
