#!/bin/bash

#check if log file exists - delete

if [ -s logrem.txt ];
  then
    rm logrem.txt;
fi

#find all empty folders and write to file
   
find $1 -type d -exec echo {} \; > logrem.txt;

#find and delete empty folders

find $1 -depth -type d -empty 2>/dev/null -exec rmdir {} \; 

