#!/bin/bash

if [ -s remlog.txt ];
  then
    rm remlog.txt;
fi



  # find . -type d -empty > remlog.txt;
  # find $1 -type d -exec echo {} \; > 1remlog.txt; 
   
   find $1 -type d -exec echo {} \; > remlog.txt; 

   find $1 -depth -type d -empty 2>/dev/null -exec rmdir {} \;

